services:
  db:
    image: mysql:latest
    container_name: pdbm_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - pdbm_network
  db-admin:
    image: phpmyadmin:latest
    container_name: pdbm_db_admin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    networks:
      - pdbm_network
  web:
   build: .
   container_name: pdbm_backend
   restart: unless-stopped
   depends_on:
     - db
   ports:
     - "3000:3000"
   environment:
     DATABASE_URL: ${DATABASE_URL_CONTAINER}
     SESSION_SECRET: ${SESSION_SECRET}
   networks:
     - pdbm_network

networks:
  pdbm_network:
    driver: bridge

volumes:
  db: